import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { M_PLUS_Rounded_1c } from "next/font/google";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const MPlusRounded1c = M_PLUS_Rounded_1c({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "都道府県別人口グラフ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="ja">
        <body className={MPlusRounded1c.className}>{children}</body>
      </html>
    </>
  );
}
